# Generated by Django 4.2.15 on 2024-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbt",
            name="no_of_questions",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
