# Generated by Django 4.2.15 on 2024-10-08 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordApp", "0002_cbt_no_of_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbt",
            name="examiner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="cbt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recordApp.cbt",
            ),
        ),
    ]
