# Generated by Django 4.2.15 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0004_course_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_form",
            name="level",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
