# Generated by Django 4.2.15 on 2024-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0005_course_form_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_form',
            name='units',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
