# Generated by Django 4.2.15 on 2024-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0010_alter_cbt_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbt",
            name="duration",
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
    ]
