# Generated by Django 4.2.15 on 2024-11-07 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recordApp", "0011_alter_cbt_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="cbt_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recordApp.cbt",
            ),
        ),
        migrations.AlterField(
            model_name="cbt",
            name="duration",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="grading",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
