# Generated by Django 4.2.15 on 2024-11-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0012_grading_cbt_id_alter_cbt_duration_alter_grading_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
