# Generated by Django 4.2.15 on 2024-11-07 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0014_rename_cbt_id_grading_cbt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grading",
            old_name="excuted_time",
            new_name="executed_time",
        ),
    ]
