# Generated by Django 4.2.15 on 2024-11-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0015_rename_excuted_time_grading_executed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grading",
            name="executed_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
