# Generated by Django 4.2.15 on 2024-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0016_grading_submitted_alter_grading_executed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="total_score",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="grading",
            name="unit",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
