# Generated by Django 4.2.15 on 2024-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0018_alter_grading_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="grade",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
