# Generated by Django 4.2.15 on 2024-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0019_grading_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_register",
            name="status",
            field=models.CharField(default="Active", max_length=25),
        ),
    ]
