# Generated by Django 4.2.15 on 2024-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0020_course_register_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="grading",
            name="point",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
