# Generated by Django 4.2.15 on 2024-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0021_grading_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbt",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
