# Generated by Django 4.2.15 on 2024-10-16 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminApp", "0002_fees_table_acceptance_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admissionApp", "0016_alter_admission_approval_aspirant"),
    ]

    operations = [
        migrations.CreateModel(
            name="invoice_table",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminApp.fees_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tuition_invoice_table",
            fields=[
                ("date_created", models.DateField(auto_created=True)),
                ("tuitInv_id", models.AutoField(primary_key=True, serialize=False)),
                ("tuition_fee", models.CharField(max_length=50)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymentApp.invoice_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="lateReg_invoice_table",
            fields=[
                ("date_created", models.DateField(auto_created=True)),
                ("regInv_id", models.AutoField(primary_key=True, serialize=False)),
                ("fee", models.CharField(max_length=20)),
                (
                    "tuition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymentApp.tuition_invoice_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="admission_invoice_table",
            fields=[
                ("date_created", models.DateField(auto_created=True)),
                ("adInv_id", models.AutoField(primary_key=True, serialize=False)),
                ("form_fee", models.CharField(max_length=50)),
                (
                    "aspirant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissionApp.aspirants_profile",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymentApp.invoice_table",
                    ),
                ),
            ],
        ),
    ]
