# Generated by Django 4.2.15 on 2024-10-22 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paymentApp", "0004_item_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
