# Generated by Django 4.2.15 on 2024-10-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentApp", "0007_invoice_table_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice_table",
            name="transaction_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
