# Generated by Django 4.2.15 on 2024-10-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentApp", "0008_alter_invoice_table_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice_table",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
