# Generated by Django 4.2.15 on 2024-11-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentApp", "0010_alter_admission_invoice_table_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission_invoice_table",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="latereg_invoice_table",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tuition_invoice_table",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
