# Generated by Django 4.2.15 on 2024-11-02 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paymentApp", "0012_alter_admission_invoice_table_aspirant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission_invoice_table",
            name="aspirant",
        ),
        migrations.AddField(
            model_name="admission_invoice_table",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
