# Generated by Django 4.2.15 on 2024-11-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("paymentApp", "0013_remove_admission_invoice_table_aspirant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="latereg_invoice_table",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tuition_invoice_table",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="acceptance_invoice_table",
            fields=[
                ("accInv_id", models.AutoField(primary_key=True, serialize=False)),
                ("acceptance_fee", models.CharField(max_length=50)),
                ("paid", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymentApp.invoice_table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
