# Generated by Django 4.2.15 on 2024-08-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_no",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "nin",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("d_o_b", models.DateField(max_length=11, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=11,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "particulars",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorce", "Divorce"),
                            ("Complicated", "Complicated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(max_length=30, null=True)),
                (
                    "next_of_kin_phone_no",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                (
                    "next_of_kin_relationship",
                    models.CharField(
                        choices=[
                            ("Mother", "Mother"),
                            ("Father", "Father"),
                            ("Brother", "Brother"),
                            ("Sister", "Sister"),
                            ("Gaurdian", "Gaurdian"),
                            ("Others", "Others"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
