# Generated by Django 4.2.15 on 2024-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="matric_no",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
