# Generated by Django 4.2.15 on 2024-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0002_remove_profile_department_remove_profile_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="other_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
