# Generated by Django 4.2.15 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0003_alter_profile_department_alter_profile_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="means_of_identity_approval",
            field=models.CharField(
                choices=[
                    ("-------", "-------"),
                    ("Unapproved", "Unapproved"),
                    ("Approved", "Approved"),
                ],
                default="Unapproved",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="particulars_approval",
            field=models.CharField(
                choices=[
                    ("-------", "-------"),
                    ("Unapproved", "Unapproved"),
                    ("Approved", "Approved"),
                ],
                default="Unapproved",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="matric_no",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
