# Generated by Django 4.2.15 on 2024-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0004_alter_users_status_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="category",
            new_name="status",
        ),
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_address",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_of_kin_email",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
