# Generated by Django 4.2.15 on 2024-11-12 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userApp", "0005_rename_category_profile_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="next_of_kin_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="next_of_kin_email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="student_table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("matric_number", models.CharField(max_length=20, unique=True)),
                ("year", models.DateField(max_length=20)),
                ("department", models.DateField(max_length=50)),
                ("date_added", models.DateTimeField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
