# Generated by Django 4.2.15 on 2024-11-12 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userApp", "0007_student_table_sequence_student_table_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_table",
            name="department",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student_table",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
