# Generated by Django 4.2.15 on 2024-11-14 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userApp", "0008_alter_student_table_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="staff_table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("department", models.CharField(max_length=50, null=True)),
                ("last_updated", models.CharField(max_length=50, null=True)),
                ("status", models.CharField(default="Active", max_length=15)),
                ("date_added", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.profile",
                    ),
                ),
                (
                    "updated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userApp.users_status",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
