# Generated by Django 4.2.15 on 2024-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0009_staff_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_table",
            name="staff_id",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
