# Generated by Django 4.2.15 on 2024-09-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="aspirants_profile",
            fields=[
                ("aspirant_id", models.AutoField(primary_key=True, serialize=False)),
                ("staff", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sponsorhip",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Parents", "Parents"),
                            ("Guardian", "Guardian"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("d_o_b", models.DateField(max_length=11, null=True)),
                ("phone_no", models.CharField(max_length=25, unique=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("Digital Marketing", "Digital Marketing"),
                            ("Business World", "Business World"),
                            ("Media Technology", "Media Technology"),
                            ("Communications", "Communications"),
                            ("Business Ethics", "Business Ethics"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("next_of_kin", models.CharField(max_length=50, null=True)),
                ("next_of_kin_number", models.CharField(max_length=15, null=True)),
                ("next_of_kin_email", models.CharField(max_length=30, null=True)),
                ("next_of_kin_address", models.CharField(max_length=50, null=True)),
                (
                    "next_of_kin_relationship",
                    models.CharField(
                        choices=[
                            ("Brother", "Brother"),
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Sister", "Sister"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("passport", models.FileField(null=True, upload_to="passportImage/")),
                ("o_levels", models.FileField(null=True, upload_to="o_levelImage/")),
                ("utme", models.FileField(null=True, upload_to="utmeImage/")),
                (
                    "national_identity",
                    models.FileField(null=True, upload_to="national_IdentityImage/"),
                ),
                ("create_time", models.DateField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="admission_approval",
            fields=[
                ("admission_id", models.AutoField(primary_key=True, serialize=False)),
                ("admitted", models.BooleanField(default=False)),
                ("approved_time", models.DateField(auto_now_add=True, null=True)),
                (
                    "aspirant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissionApp.aspirants_profile",
                    ),
                ),
                (
                    "officer_incharge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
