# Generated by Django 4.2.15 on 2024-09-20 10:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aspirants_profile",
            fields=[
                ("aspirant_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("d_o_b", models.DateField(max_length=11, null=True)),
                ("phone_no", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(max_length=20, unique=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("next_of_kin", models.CharField(max_length=20, null=True)),
                ("next_of_kin_number", models.CharField(max_length=15, null=True)),
                ("next_of_kin_email", models.CharField(max_length=30, null=True)),
                (
                    "next_of_kin_relationship",
                    models.CharField(
                        choices=[
                            ("Brother", "Brother"),
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Sister", "Sister"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("passport", models.FileField(null=True, upload_to="passportImage/")),
                ("o_levels", models.FileField(null=True, upload_to="o_levelsImage/")),
                ("utme", models.FileField(null=True, upload_to="utmeImage/")),
                ("password", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="admission_approval",
            fields=[
                ("admission_id", models.AutoField(primary_key=True, serialize=False)),
                ("admitted", models.BooleanField(default=False)),
                (
                    "aspirant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissionApp.aspirants_profile",
                    ),
                ),
            ],
        ),
    ]
