# Generated by Django 4.2.15 on 2024-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirants_profile",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
