# Generated by Django 4.2.15 on 2024-09-27 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aspirants_profile",
            old_name="staff",
            new_name="aspirant",
        ),
    ]
