# Generated by Django 4.2.15 on 2024-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0002_alter_aspirants_profile_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="country",
        ),
        migrations.AddField(
            model_name="aspirants_profile",
            name="username",
            field=models.CharField(
                blank=True, default="none", max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="aspirants_profile",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="aspirants_profile",
            name="o_levels",
            field=models.FileField(null=True, unique=True, upload_to="o_levelImage/"),
        ),
        migrations.AlterField(
            model_name="aspirants_profile",
            name="passport",
            field=models.FileField(null=True, unique=True, upload_to="passportImage/"),
        ),
        migrations.AlterField(
            model_name="aspirants_profile",
            name="utme",
            field=models.FileField(null=True, unique=True, upload_to="utmeImage/"),
        ),
    ]
