# Generated by Django 4.2.15 on 2024-09-27 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0002_rename_staff_aspirants_profile_aspirant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aspirants_profile",
            old_name="aspirant",
            new_name="student",
        ),
    ]
