# Generated by Django 4.2.15 on 2024-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0003_rename_aspirant_aspirants_profile_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="d_o_b",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="next_of_kin",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="next_of_kin_number",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="next_of_kin_relationship",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="phone_no",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="student",
        ),
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="user",
        ),
    ]
