# Generated by Django 4.2.15 on 2024-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0003_remove_aspirants_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirants_profile",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
