# Generated by Django 4.2.15 on 2024-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0004_alter_aspirants_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirants_profile",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
