# Generated by Django 4.2.15 on 2024-09-30 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0004_remove_aspirants_profile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirants_profile",
            name="gender",
        ),
    ]
