# Generated by Django 4.2.15 on 2024-10-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admissionApp", "0007_alter_aspirants_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aspirants_profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
