# Generated by Django 4.2.15 on 2024-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0011_rename_create_time_aspirants_profile_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspirants_profile",
            name="registration_status",
            field=models.BooleanField(default=False),
        ),
    ]
