# Generated by Django 4.2.15 on 2024-10-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0013_alter_aspirants_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission_approval",
            old_name="admitted",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="admission_approval",
            name="aspirant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissionApp.aspirants_profile",
            ),
        ),
    ]
