# Generated by Django 4.2.15 on 2024-10-03 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0014_rename_admitted_admission_approval_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission_approval",
            old_name="approved_time",
            new_name="approved_date",
        ),
    ]
