# Generated by Django 4.2.15 on 2024-10-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0015_rename_approved_time_admission_approval_approved_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission_approval",
            name="aspirant",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissionApp.aspirants_profile",
            ),
        ),
    ]
