# Generated by Django 4.2.15 on 2024-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissionApp", "0017_alter_aspirants_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission_approval",
            name="acceptance_fee",
            field=models.BooleanField(default=False),
        ),
    ]
