# Generated by Django 4.2.15 on 2024-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fees_table",
            name="acceptance_fee",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
